In [23]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [24]:
Cancer = datasets.load_breast_cancer()

In [25]:
Cancer.data.shape, Cancer.target.shape

((569, 30), (569,))

In [26]:
Atribut_Training, Atribut_Testing, Kelas_Training, Kelas_Testing = train_test_split(Cancer.data, Cancer.target, test_size=0.4,random_state=0)

In [27]:
Atribut_Training.shape

(341, 30)

In [28]:
Atribut_Testing.shape

(228, 30)

In [29]:
Kelas_Training.shape

(341,)

In [30]:
Kelas_Testing.shape

(228,)

In [31]:
gnb =GaussianNB()
classifier = gnb.fit(Atribut_Training,Kelas_Training)

In [32]:
classifier.score(Atribut_Testing,Kelas_Testing)

0.9298245614035088

In [33]:
from sklearn.model_selection import cross_val_score
akurasi_cross_val = cross_val_score(classifier, Cancer.data, Cancer.target,cv=5)

In [34]:
akurasi_cross_val

array([0.92105263, 0.92105263, 0.94736842, 0.94736842, 0.95575221])

In [35]:
rerata_akurasi = akurasi_cross_val.mean()
rerata_akurasi

0.9385188635305075

In [36]:
from sklearn.metrics import confusion_matrix, classification_report
prediksi = classifier.predict(Atribut_Testing)
confusion_matrix(prediksi,Kelas_Testing)

array([[ 74,   7],
       [  9, 138]], dtype=int64)

In [37]:
print(classification_report(prediksi, Kelas_Testing))

              precision    recall  f1-score   support

           0       0.89      0.91      0.90        81
           1       0.95      0.94      0.95       147

    accuracy                           0.93       228
   macro avg       0.92      0.93      0.92       228
weighted avg       0.93      0.93      0.93       228



In [38]:
from sklearn.model_selection import cross_val_score, cross_val_predict
akurasi_cross_val = cross_val_score(classifier, Cancer.data, Cancer.target,cv=10)
akurasi_cross_val

array([0.94736842, 0.87719298, 0.89473684, 0.92982456, 0.94736842,
       0.96491228, 0.92982456, 0.96491228, 0.94736842, 0.96428571])

In [39]:
rerata_akurasi = akurasi_cross_val.mean()
rerata_akurasi

0.9367794486215537

In [40]:
y_pred = cross_val_predict(classifier, Cancer.data, Cancer.target,cv=10)
conf_mat= confusion_matrix(Cancer.target, y_pred)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

In [41]:
conf_mat

array([[188,  24],
       [ 12, 345]], dtype=int64)

In [42]:
print(classification_report(Cancer.target,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.89      0.91       212
           1       0.93      0.97      0.95       357

    accuracy                           0.94       569
   macro avg       0.94      0.93      0.93       569
weighted avg       0.94      0.94      0.94       569

